name: Deploy Javadoc

permissions:
  contents: write
  
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adapt'
          
      - name: Generate Javadoc with Maven
        run: mvn javadoc:aggregate
        shell: bash
        
      - name: Push documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/apidocs
          force_orphan: true
