name: Deploy Javadoc

permissions:
  contents: write
  
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: dev-vince/Javadoc-publisher.yml@1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 8
          target-folder: javadoc
          project: maven 
